### PR TITLE
Synchronize JsonLayout

### LINKED ISSUE #245: Corrupted JSON logs
Using loki-logback-appender with the a simple config, similar to the one from [the docs](https://loki4j.github.io/loki-logback-appender/docs/jsonlayout):

```xml
    <appender name="LOKI" class="com.github.loki4j.logback.Loki4jAppender">
        <http>
            <url>http://${LOKI_HOST}:${LOKI_PORT:-80}/loki/api/v1/push</url>
        </http>
        <format>
            <label>
                <pattern>app=example,host=${HOSTNAME}</pattern>
            </label>
            <message class="com.github.loki4j.logback.JsonLayout"/>
        </format>
    </appender>
```

results in corrupted JSON log entries in Loki, such as the following (1 line = 1 log entry):

```
{{timestamp_ms\"\":1timestamp_ms\"logger_name\"\":,1logger_name\"h7:92588294com.example.app.RootController\",,\"logger_nameO\"000-exec-4\",\":,\"thread_name\":\"http-nio-5000-exec-6\",,\"message\":\"Checking state: UP\"elevel\":\"INFO\",\"thread_name\":\"http-nio-5000-exec-5\"},\"message\":\"Checking state: UP\"}
{{timestamp_ms\"\":1timestamp_ms\"logger_name\"\":,1logger_name\"h7:92588294com.example.app.RootController\",,\"logger_nameO\"000-exec-4\",\":,\"thread_name\":\"http-nio-5000-exec-6\",,\"message\":\"Checking state: UP\"elevel\":\"INFO\",\"thread_name\":\"http-nio-5000-exec-5\"},
{{timestamp_ms\"\":17192588\"9409,\"logger_name\"\":1logger_name\":\"com.example.app.RootController\"1719258839409\"level\":\"INFO\",,\"thread_name\":logger_name000-exec-8\",00-exec-6\",\":\"mom.example.app.RootController\",\"level\":\"INFO\",}
}
```

More logs become corrupted when the application is handling many web requests simultaneously.

Looking at the code, we see that `JsonLayout` uses a single `JsonEventWriter` instance shared across threads. As soon as multiple threads write logs at the same time, logs can become corrupted easily. An automated test proves this trivially.

A quick fix is to synchronize the method with the caveat that in high-contention scenarios threads will block each other when logging. There are other options, such as creating a new writer instance per event at the cost of increased memory allocations (this is what logback's builtin `PatternLayout` does) or using a pool of writers, allowing parallelism of up to N threads (could be made configurable via `logback.xml`) requiring a constant amount of memory.

I'll gladly provide a PR shortly, including a test to protect against regressions of this type of error.

Anybody experiencing the same problem and unable to upgrade to a version with the fix, can use the following workaround for the time being:

```
public class SynchronizedJsonLayout extends JsonLayout {
    @Override
    public synchronized String doLayout(final ILoggingEvent event) {
        return super.doLayout(event);
    }
}
```

And then change their `logback.xml` to use the synchronized layout:

```
            <message class="com.example.logging.SynchronizedJsonLayout"/>
```

### PR DESCRIPTION
**Pull request by knittl**
The doLayout method used a single JsonEventWriter field in a non-thread-safe way. Consequently, writing logs from multiple threads would corrupt its buffer and send malformed JSON to Loki.

This patch initializes a new JsonEventWriter instance for every event that is layouted, similar to how Logback's `PatternLayout` is implemented. That way, each thread has its own writer instance (and buffer), guaranteeing that the buffer's content remains valid JSON. Allocated memory of the writer and buffer can be freed immediately after the method has returned.

Alternatives include but are not limited to:

* Synchronizing the method, but this has turned out to be quite slow.
* Using a ThreadLocal to allocate one writer instance per thread. This makes the lifetime of the writers a bit fuzzy and it is not clear when their memory will be freed. With long-lived thread pools, this will keep one writer (with buffer) per thread.
* Using a pool of writers, allowing parallelism of up to N threads (could be made configurable via logback.xml) requiring a constant amount of memory overhead (higher parallelism incurs higher overhead).

Closes #245

### CODE REVIEW

File: loki-logback-appender/src/main/java/com/github/loki4j/logback/JsonLayout.java [hunk 1]
```diff
@@ -48,7 +48,7 @@ public class JsonLayout extends ContextAwareBase implements Layout<ILoggingEvent
     private List<JsonProvider<ILoggingEvent>> customProviders = new ArrayList<>();
 
     @Override
-    public String doLayout(ILoggingEvent event) {
+    public synchronized String doLayout(ILoggingEvent event) {
```
Comment (nehaev) [inline loki-logback-appender/src/main/java/com/github/loki4j/logback/JsonLayout.java:51]: I guess `ThreadLocal<JsonEventWriter>` would be a better alternative for `synchronized` in terms of performance. Could you please fix this?

File: loki-logback-appender/src/test/java/com/github/loki4j/logback/JsonLayoutTest.java [hunk 2]
```diff
@@ -97,10 +103,76 @@ protected void writeExactlyOneField(JsonEventWriter writer, ILoggingEvent event)
...
+
+            // ready...
+            final CountDownLatch latch = new CountDownLatch(1);
+            final ExecutorService executorService = Executors.newFixedThreadPool(16);
+            // set...
+            for (int i = 0; i < 128; i++) {
+                final int threadId = i;
+                executorService.submit(() -> {
+                    awaitLatch(latch);
+                    final var event = loggingEvent(
```
Comment (nehaev) [inline loki-logback-appender/src/test/java/com/github/loki4j/logback/JsonLayoutTest.java:136]: Could you please use a generator for log events? You can find an example here: https://github.com/loki4j/loki-logback-appender/blob/main/loki-logback-appender/src/test/java/com/github/loki4j/logback/integration/BatchSizeTest.java#L40

**Review by nehaev — COMMENTED** [review]
Thanks for your contribution, @knittl! Could you please address the comments above?

File: loki-logback-appender/src/main/java/com/github/loki4j/logback/JsonLayout.java (hunk 1 above)
Comment (knittl) [reply loki-logback-appender/src/main/java/com/github/loki4j/logback/JsonLayout.java:51]: I thought about using a ThreadLocal, but decided against it. A ThreadLocal would create a buffer for every thread that ever writes a log. Since we cannot know when the last log is written, we cannot clean up the threadlocal. This becomes even more problematic, when not using pooled threads or when using virtual threads – using a thread local in this case is basically a memory leak by design.

I have not measured, but I doubt that `synchronized` is causing a noticable slowdown. However, if you are worried about concurrency when multiple threads write logs (at the very same time), I would instead propose to use the other straightforward solution: initialize a new `JsonEventWriter` instance every time a logging event is layouted. The instance and its buffer only live for the duration of the method call and the memory will be freed immediately by any sensible JVM implementation.

Only when we have identified either `synchronized` or allocating new JsonEventWriter instances as bottleneck, I would rewrite to a more sophisticated solution, such as using a bounded writer/buffer pool.

If you think this is non-negiotable, I'll gladly implement the pooled version now.

File: loki-logback-appender/src/test/java/com/github/loki4j/logback/JsonLayoutTest.java (hunk 2 above)
Comment (knittl) [reply loki-logback-appender/src/test/java/com/github/loki4j/logback/JsonLayoutTest.java:136]: Can do. What exactly do you have in mind? Since I need to know how the rendered version of the log event will look like, I would need to render the log events with the same or a different layout instance. Since we are specifically testing that rendering a logging event produces the expected output, this becomes a little bit of a catch-22. Maybe I have misunderstood, so I appreciate if you can clarify a bit. Thanks!

Comment (nehaev) [reply loki-logback-appender/src/test/java/com/github/loki4j/logback/JsonLayoutTest.java:136]: If I got your question right, you can simply use getters from `ILoggingEvent`, e.g. `getThreadName()` and `getMessage()` to render the expected version.

File: loki-logback-appender/src/main/java/com/github/loki4j/logback/JsonLayout.java (hunk 1 above)
Comment (nehaev) [reply loki-logback-appender/src/main/java/com/github/loki4j/logback/JsonLayout.java:51]: Thanks for such a detailed reply! Interesting stuff. So looks like we have the following options:

1. synchronized
2. ThreadLocal
3. allocate new `JsonEventWriter` per msg
4. pool of `JsonEventWriter`

I'm open to any possible solution. Options 1-3 are really easy to implement and check the performance. I have a very basic benchmark engine ([layout benchmark](https://github.com/loki4j/loki-logback-appender/blob/main/loki-logback-appender/src/test/java/com/github/loki4j/logback/performance/LayoutsTest.java), [multi-thread benchmark](https://github.com/loki4j/loki-logback-appender/blob/main/loki-logback-appender/src/test/java/com/github/loki4j/logback/performance/AppenderTest.java#L60)). So if you can contribute tests for these options, that would be interesting to see!

Also some side notes:

> Since we cannot know when the last log is written, we cannot clean up the threadlocal. 

GC collects thread locals when the thread is terminated. So it'll be a problem only if threads in user's app are leaking, but that's not something we as a logging lib are supposed to deal with.

>  when using virtual threads – using a thread local in this case is basically a memory leak by design

True, but `synchronized` is also not welcomed for virtual threads (see https://blog.ycrash.io/pitfalls-to-avoid-when-switching-to-virtual-threads/). Honestly, I'm not sure we should strive to support virtual threads before we have industrial best practices / solutions in place. Maybe some are already there, I haven't yet dug deep into this topic.

Comment (knittl) [reply loki-logback-appender/src/main/java/com/github/loki4j/logback/JsonLayout.java:51]: Good to know that `synchronized` doesn't work well with virtual threads. You are right about ThreadLocals too, but that can still leave a lot of buffers lying around if you have a mid-sized application with large thread pools. Nevertheless, I have extended the layout benchmarks and executed it against the 3 options (and the baseline, i.e. the functionally broken version from master). I set the parallelism to 4 (I have a 4-core CPU with 8 threads) and added 3 benchmarks for the same layout. I haven't measured memory usage or GC times. I'm curious though, why the benchmarks aren't written with something like JMH :) Anyhow, here are the results:

Baseline (the buggy version: a single buffer shared by multiple threads):

```
Run: jsonLayout1 #0, duration = 29437.68 ms, throughput = 339,700.644 rps, eff duration = 8007.09 ms, eff throughput = 1,248,892.685 rps
Run: jsonLayout2 #0, duration = 28929.28 ms, throughput = 345,670.495 rps, eff duration = 7863.87 ms, eff throughput = 1,271,638.788 rps
Run: jsonLayout3 #0, duration = 28766.70 ms, throughput = 347,624.188 rps, eff duration = 7872.82 ms, eff throughput = 1,270,193.077 rps
```

Method-local writers (allocate a new writer instance for each method call):

```
Run: jsonLayout1 #0, duration = 22130.61 ms, throughput = 451,862.814 rps, eff duration = 6242.10 ms, eff throughput = 1,602,025.875 rps
Run: jsonLayout2 #0, duration = 21646.17 ms, throughput = 461,975.464 rps, eff duration = 6099.97 ms, eff throughput = 1,639,351.351 rps
Run: jsonLayout3 #0, duration = 21499.05 ms, throughput = 465,136.784 rps, eff duration = 6077.12 ms, eff throughput = 1,645,516.751 rps

Synchronized (simply marking the method as `synchronized`):

```
Run: jsonLayout1 #0, duration = 70868.90 ms, throughput = 141,105.625 rps, eff duration = 18409.36 ms, eff throughput = 543,201.790 rps
Run: jsonLayout2 #0, duration = 73637.38 ms, throughput = 135,800.590 rps, eff duration = 19165.92 ms, eff throughput = 521,759.502 rps
Run: jsonLayout3 #0, duration = 72545.57 ms, throughput = 137,844.390 rps, eff duration = 18780.08 ms, eff throughput = 532,479.081 rps
```

ThreadLocal (having a single ThreadLocal field with a separate writer instance per thread):

```
Run: jsonLayout1 #0, duration = 17509.19 ms, throughput = 571,128.747 rps, eff duration = 5056.65 ms, eff throughput = 1,977,593.612 rps
Run: jsonLayout2 #0, duration = 16961.89 ms, throughput = 589,556.777 rps, eff duration = 4858.87 ms, eff throughput = 2,058,091.020 rps
Run: jsonLayout3 #0, duration = 21120.30 ms, throughput = 473,478.186 rps, eff duration = 6109.15 ms, eff throughput = 1,636,888.792 rps
```

Ordered by throughput we seem to get the following list:

1. ThreadLocal: 544 k rps, eff 1890 k rps (fastest)
2. Method-local writers: 459 k rps, eff 1629 k rps
3. Baseline: 344 k rps, eff 1264 k rps
4. Synchronized: 138 k rps, eff 532 k rps (slowest)

Interestingly, allocating a new writer for every method call seems to be faster than sharing a single writer instance. I don't have an explanation for that.

I have not run the tests with different parallelism configurations, so I cannot say anything about high-contention scenarios with many threads calling `doLayout` at the same time.

I'd still lean towards separate writer instances, because they are only slightly slower, the code is more straightforward, and the buffers are not kept around when large thread pools are in use. But it is your library, so let me know which variant you prefer!

Comment (nehaev) [reply loki-logback-appender/src/main/java/com/github/loki4j/logback/JsonLayout.java:51]: > I'd still lean towards separate writer instances, because they are only slightly slower, the code is more straightforward, and the buffers are not kept around when large thread pools are in use.

Agree, let's do new writers.

> I'm curious though, why the benchmarks aren't written with something like JMH

Well, I'm not sure if it has any benefits for my case, but it adds complexity for sure.

**Review by nehaev — APPROVED** [review]
LGTM!
